name: Packer Install Dev

on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: environment   
          required: true
          default: dev

# env:
#   GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_PRIVATE_KEY_DEV }}

jobs:
  packer:
    runs-on: core-app
    name: packer-build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.PACKER_KEY_DEV }} #This will be JSON key of SA with owner permissions

      - id: set-up-cloud-sdk
        uses: google-github-actions/setup-gcloud@v0

      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      # build artifact
      - name: Build Artifact
        # if: github.ref == 'refs/heads/main'
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -var-file=./environment/dev.json"
          target: packer.json
        env:
          PACKER_LOG: 1
          SHA: ${{ steps.vars.outputs.sha_short }}
